"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Empty, EmptyDescription, EmptyHeader, EmptyMedia, EmptyTitle } from "@/components/ui/empty";
import { Field, FieldDescription, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { authClient } from "@/lib/auth-client";
import { ServerStack01Icon, Link01Icon, PlusSignIcon, Delete02Icon, Wrench01Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";
import { useState } from "react";
import { toast } from "sonner";
import useSWR from "swr";

type Integration = { id: string; name: string; endpoint: string; transport: string; enabled: boolean; links?: Array<{ id: string; scope: "organization" | "chat" | "agent"; chatId: string | null; agentId: string | null; allowedTools: string[] }> };
type Scope = "organization" | "chat" | "agent";
const fetcher = async (url: string) => { const response = await fetch(url); if (!response.ok) throw new Error("Unable to load MCP integrations"); return response.json(); };
async function request(url: string, init?: RequestInit) { const response = await fetch(url, { ...init, headers: { "Content-Type": "application/json", ...init?.headers } }); if (!response.ok) { const payload = (await response.json().catch(() => null)) as { message?: string; error?: string } | null; throw new Error(payload?.message ?? payload?.error ?? "Request failed"); } return response.json(); }

export function WorkspaceTools() {
  const { data: organization } = authClient.useActiveOrganization();
  const { data: integrations, mutate } = useSWR<Integration[]>(organization?.id ? "/api/automation/mcp" : null, fetcher);
  const [form, setForm] = useState({ name: "", endpoint: "", credentialRef: "" });
  const [scope, setScope] = useState<{ type: Scope; targetId: string; allowedTools: string }>({ type: "organization", targetId: "", allowedTools: "" });
  const [saving, setSaving] = useState(false);

  const create = async () => { if (!organization?.id || !form.name.trim() || !form.endpoint.trim()) return; setSaving(true); try { await request("/api/automation/mcp", { method: "POST", body: JSON.stringify({ ...form, organizationId: organization.id, transport: "streamable_http", credentialRef: form.credentialRef || null }) }); setForm({ name: "", endpoint: "", credentialRef: "" }); await mutate(); toast.success("MCP connection added"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to add MCP connection"); } finally { setSaving(false); } };
  const remove = async (id: string) => { try { await request(`/api/automation/mcp/${id}`, { method: "DELETE" }); await mutate(); toast.success("MCP connection removed"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to remove MCP connection"); } };
  const link = async (integrationId: string) => { if ((scope.type !== "organization" && !scope.targetId.trim())) { toast.error("Add a chat or agent ID for this scope"); return; } try { await request(`/api/automation/mcp/${integrationId}/links`, { method: "POST", body: JSON.stringify({ scope: scope.type, ...(scope.type === "chat" ? { chatId: scope.targetId } : {}), ...(scope.type === "agent" ? { agentId: scope.targetId } : {}), allowedTools: scope.allowedTools.split(",").map((item) => item.trim()).filter(Boolean) }) }); setScope({ type: "organization", targetId: "", allowedTools: "" }); await mutate(); toast.success("Tool scope linked"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to link tool scope"); } };
  const unlink = async (id: string) => { try { await request(`/api/automation/mcp/links/${id}`, { method: "DELETE" }); await mutate(); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to unlink tool scope"); } };

  return <div className="flex flex-col gap-6">
    <Card>
      <CardHeader><CardTitle className="flex items-center gap-2"><HugeiconsIcon icon={ServerStack01Icon} strokeWidth={2} /> Connect a tool server</CardTitle><CardDescription>Connect a remote MCP server once, then decide which chats or agents may use it.</CardDescription></CardHeader>
      <CardContent><FieldGroup><div className="grid gap-4 md:grid-cols-3"><Field><FieldLabel htmlFor="mcp-name">Connection name</FieldLabel><Input id="mcp-name" onChange={(event) => setForm((current) => ({ ...current, name: event.target.value }))} placeholder="Research tools" value={form.name} /></Field><Field><FieldLabel htmlFor="mcp-endpoint">Server endpoint</FieldLabel><Input id="mcp-endpoint" onChange={(event) => setForm((current) => ({ ...current, endpoint: event.target.value }))} placeholder="https://mcp.example.com" value={form.endpoint} /></Field><Field><FieldLabel htmlFor="mcp-credential">Credential reference</FieldLabel><Input id="mcp-credential" onChange={(event) => setForm((current) => ({ ...current, credentialRef: event.target.value }))} placeholder="Optional secret reference" value={form.credentialRef} /><FieldDescription>Secrets are referenced, never displayed here.</FieldDescription></Field></div><Button disabled={saving || !form.name.trim() || !form.endpoint.trim()} onClick={() => void create()}><HugeiconsIcon icon={PlusSignIcon} data-icon="inline-start" strokeWidth={2} /> Add connection</Button></FieldGroup></CardContent>
    </Card>
    {!integrations?.length ? <Empty className="min-h-56 border border-dashed"><EmptyHeader><EmptyMedia variant="icon"><HugeiconsIcon icon={Wrench01Icon} /></EmptyMedia><EmptyTitle>No tool servers connected</EmptyTitle><EmptyDescription>Connect an MCP server to make external tools available to approved agents and chats.</EmptyDescription></EmptyHeader></Empty> : <div className="grid gap-4 xl:grid-cols-2">{integrations.map((integration) => <Card key={integration.id}><CardHeader><div className="flex items-start justify-between gap-3"><div className="min-w-0"><CardTitle className="truncate text-base">{integration.name}</CardTitle><CardDescription className="truncate">{integration.endpoint}</CardDescription></div><div className="flex items-center gap-2"><Badge variant={integration.enabled ? "secondary" : "outline"}>{integration.enabled ? "Connected" : "Disabled"}</Badge><Button aria-label={`Remove ${integration.name}`} onClick={() => void remove(integration.id)} size="icon" variant="ghost"><HugeiconsIcon icon={Delete02Icon} strokeWidth={2} /></Button></div></div></CardHeader><CardContent className="flex flex-col gap-3"><div className="flex flex-col gap-2">{(integration.links ?? []).map((item) => <div className="flex items-center justify-between gap-2 rounded-lg border px-3 py-2 text-xs" key={item.id}><span className="truncate"><Badge className="mr-2" variant="outline">{item.scope}</Badge>{item.chatId ?? item.agentId ?? "Entire workspace"}{item.allowedTools.length ? ` · ${item.allowedTools.join(", ")}` : " · all tools"}</span><Button aria-label="Remove tool scope" onClick={() => void unlink(item.id)} size="icon" variant="ghost"><HugeiconsIcon icon={Delete02Icon} strokeWidth={2} /></Button></div>)}</div><Separator /><div className="grid gap-2 sm:grid-cols-[130px_minmax(0,1fr)]"><Select onValueChange={(value) => setScope((current) => ({ ...current, type: String(value) as Scope, targetId: "" }))} value={scope.type}><SelectTrigger size="sm"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="organization">Workspace</SelectItem><SelectItem value="chat">Chat</SelectItem><SelectItem value="agent">Agent</SelectItem></SelectGroup></SelectContent></Select><Input className="h-8 text-xs" disabled={scope.type === "organization"} onChange={(event) => setScope((current) => ({ ...current, targetId: event.target.value }))} placeholder={scope.type === "organization" ? "Available to the whole workspace" : `${scope.type} ID`} value={scope.targetId} /></div><div className="flex gap-2"><Input className="h-8 text-xs" onChange={(event) => setScope((current) => ({ ...current, allowedTools: event.target.value }))} placeholder="Allowed tools, comma separated (optional)" value={scope.allowedTools} /><Button onClick={() => void link(integration.id)} size="sm"><HugeiconsIcon icon={Link01Icon} data-icon="inline-start" strokeWidth={2} /> Link</Button></div></CardContent></Card>)}</div>}
  </div>;
}
