import { cn } from "@/lib/utils";
import { AuthClientProvider } from "@/providers/auth-client-provider";
import { PointerProvider } from "@/providers/pointer-provider";
import { SWRProvider } from "@/providers/swr-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import { AutumnProvider } from "autumn-js/react";
import type { Metadata } from "next";
import { ReactNode } from "react";
import { Toaster } from "sonner";
import "./globals.css";
import { env } from "process";

export const viewport = {
  maximumScale: 1, // Disable auto-zoom on mobile Safari
};

// Use system font stack to avoid build-time font fetching

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="snap-y snap-mandatory scroll-smooth"
    >
      <body className={cn("font-sans", "antialiased")}>
        <ThemeProvider>
          <AutumnProvider
            betterAuthUrl={env.NEXT_PUBLIC_BETTER_AUTH_URL}
          >
            <SWRProvider>
              <PointerProvider>
                <AuthClientProvider>{children}</AuthClientProvider>
                <Toaster />
              </PointerProvider>
            </SWRProvider>
          </AutumnProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}

// TODO button active style
