"use client";

import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectGroup, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { useChatSettings, type AgentOption, type ChatSettings, type ChatSettingsForm, type KnowledgeBaseOption } from "@/hooks/use-chat-settings";
import { Settings01Icon, UserAdd01Icon, UserGroupIcon, Wrench01Icon } from "@hugeicons/core-free-icons";
import { HugeiconsIcon } from "@hugeicons/react";

export function ChatSettingsDialog({ chatId }: { chatId: string }) {
  const settings = useChatSettings(chatId);
  return <>
    <Button aria-label="Chat settings" className="absolute top-3 right-3 z-20" onClick={() => settings.setOpen(true)} size="icon" variant="ghost"><HugeiconsIcon icon={Settings01Icon} strokeWidth={2} /></Button>
    <Dialog onOpenChange={settings.setOpen} open={settings.open}>
      <DialogContent className="max-h-[88vh] overflow-y-auto sm:max-w-3xl"><DialogHeader><DialogTitle>Chat settings</DialogTitle></DialogHeader>
        {settings.error ? <p className="text-sm text-destructive">{settings.error.message}</p> : !settings.data ? <p className="text-sm text-muted-foreground">Loading settings…</p> : <Tabs defaultValue="conversation"><TabsList className="w-full" variant="line"><TabsTrigger value="conversation"><HugeiconsIcon data-icon="inline-start" icon={Settings01Icon} strokeWidth={2} />Conversation</TabsTrigger><TabsTrigger value="access"><HugeiconsIcon data-icon="inline-start" icon={UserGroupIcon} strokeWidth={2} />Access</TabsTrigger><TabsTrigger value="capabilities"><HugeiconsIcon data-icon="inline-start" icon={Wrench01Icon} strokeWidth={2} />Capabilities</TabsTrigger></TabsList><TabsContent className="pt-5" value="conversation"><ConversationPanel data={settings.data} form={settings.form} save={settings.save} saving={settings.saving} setForm={settings.setForm} /></TabsContent><TabsContent className="pt-5" value="access"><AccessPanel addMember={settings.addMember} data={settings.data} memberEmail={settings.memberEmail} removeMember={settings.removeMember} setMemberEmail={settings.setMemberEmail} updateMember={settings.updateMember} /></TabsContent><TabsContent className="pt-5" value="capabilities"><CapabilitiesPanel addAgent={settings.addAgent} agentData={settings.agentData} agentId={settings.agentId} data={settings.data} form={settings.form} knowledgeBaseData={settings.knowledgeBaseData} removeAgent={settings.removeAgent} save={settings.save} setAgentId={settings.setAgentId} setForm={settings.setForm} /></TabsContent></Tabs>}
      </DialogContent>
    </Dialog>
  </>;
}

function ConversationPanel({ data, form, setForm, save, saving }: { data: ChatSettings; form: ChatSettingsForm; setForm: React.Dispatch<React.SetStateAction<ChatSettingsForm>>; save: () => Promise<void>; saving: boolean }) {
  const disabled = !data.access.canManageChat;
  return <Card><CardHeader><CardTitle>Conversation defaults</CardTitle><CardDescription>These instructions and visibility rules apply to this chat only.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4"><Input disabled={disabled} onChange={(event) => setForm((current) => ({ ...current, title: event.target.value }))} placeholder="Chat title" value={form.title} /><Input disabled={disabled} onChange={(event) => setForm((current) => ({ ...current, description: event.target.value }))} placeholder="Description" value={form.description} /><Textarea className="min-h-28" disabled={disabled} onChange={(event) => setForm((current) => ({ ...current, instructions: event.target.value }))} placeholder="Rules and instructions for this chat" value={form.instructions} /><div className="flex flex-wrap items-center gap-4"><label className="flex items-center gap-2 text-sm"><Checkbox checked={form.orchestrationEnabled} disabled={disabled} onCheckedChange={(checked) => setForm((current) => ({ ...current, orchestrationEnabled: checked === true }))} />Enable orchestration</label><Select disabled={disabled} onValueChange={(value) => setForm((current) => ({ ...current, visibility: String(value) as "private" | "public" }))} value={form.visibility}><SelectTrigger className="w-32"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="private">Private</SelectItem><SelectItem value="public">Public</SelectItem></SelectGroup></SelectContent></Select></div><Button disabled={saving || (!data.access.canManageChat && !data.access.canManageKnowledge)} onClick={() => void save()}>{saving ? "Saving…" : "Save conversation"}</Button></CardContent></Card>;
}

function AccessPanel({ data, memberEmail, setMemberEmail, addMember, removeMember, updateMember }: { data: ChatSettings; memberEmail: string; setMemberEmail: (value: string) => void; addMember: () => Promise<void>; removeMember: (id: string) => Promise<void>; updateMember: (id: string, changes: Record<string, unknown>) => Promise<void> }) {
  return <Card><CardHeader><CardTitle className="flex items-center gap-2"><HugeiconsIcon icon={UserGroupIcon} strokeWidth={2} /> People in this chat</CardTitle><CardDescription>Chat access is separate from workspace membership. Owners can grant narrow capabilities without changing workspace roles.</CardDescription></CardHeader><CardContent className="flex flex-col gap-4">{data.access.canInviteMembers && <div className="flex gap-2"><Input onChange={(event) => setMemberEmail(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") void addMember(); }} placeholder="Workspace member email" value={memberEmail} /><Button aria-label="Add member" onClick={() => void addMember()} size="icon"><HugeiconsIcon icon={UserAdd01Icon} strokeWidth={2} /></Button></div>}<div className="flex flex-col gap-2">{data.members.map((member) => <div className="flex flex-col gap-3 rounded-xl border p-3 sm:flex-row sm:items-center sm:justify-between" key={member.id}><div className="min-w-0"><p className="truncate text-sm font-medium">{member.user?.name || member.user?.email || member.userId}</p><div className="flex flex-wrap items-center gap-2"><Badge variant={member.role === "owner" ? "default" : "secondary"}>{member.role}</Badge>{member.canInvite && <Badge variant="outline">Invite</Badge>}{member.canManageAgents && <Badge variant="outline">Agents</Badge>}{member.canManageKnowledge && <Badge variant="outline">Knowledge</Badge>}</div></div><div className="flex items-center gap-2">{data.access.canManageChat && member.role !== "owner" && <><Select onValueChange={(value) => void updateMember(member.id, { role: String(value) })} value={member.role}><SelectTrigger aria-label="Member role" className="w-28" size="sm"><SelectValue /></SelectTrigger><SelectContent><SelectGroup><SelectItem value="member">Member</SelectItem><SelectItem value="admin">Admin</SelectItem></SelectGroup></SelectContent></Select><div className="hidden items-center gap-2 md:flex"><Checkbox aria-label="Can invite" checked={member.canInvite} onCheckedChange={(checked) => void updateMember(member.id, { canInvite: checked === true })} /><Checkbox aria-label="Can manage agents" checked={member.canManageAgents} onCheckedChange={(checked) => void updateMember(member.id, { canManageAgents: checked === true })} /><Checkbox aria-label="Can manage knowledge" checked={member.canManageKnowledge} onCheckedChange={(checked) => void updateMember(member.id, { canManageKnowledge: checked === true })} /></div></>}{member.role !== "owner" && (data.access.canManageChat || member.userId === data.access.currentUserId) && <Button aria-label="Remove member" onClick={() => void removeMember(member.id)} size="sm" variant="ghost">Remove</Button>}</div></div>)}</div></CardContent></Card>;
}

function CapabilitiesPanel({ data, form, setForm, knowledgeBaseData, agentData, agentId, setAgentId, addAgent, removeAgent, save }: { data: ChatSettings; form: ChatSettingsForm; setForm: React.Dispatch<React.SetStateAction<ChatSettingsForm>>; knowledgeBaseData?: KnowledgeBaseOption[]; agentData?: AgentOption[]; agentId: string; setAgentId: (value: string) => void; addAgent: () => Promise<void>; removeAgent: (id: string) => Promise<void>; save: () => Promise<void> }) {
  return <div className="flex flex-col gap-4"><Card><CardHeader><CardTitle>Knowledge bases</CardTitle><CardDescription>Select the sources available to this chat and its enabled agents.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{(knowledgeBaseData ?? []).map((base) => <label className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm" key={base.id}><Checkbox checked={form.knowledgeBaseIds.includes(base.id)} disabled={!data.access.canManageKnowledge} onCheckedChange={(checked) => setForm((current) => ({ ...current, knowledgeBaseIds: checked === true ? [...current.knowledgeBaseIds, base.id] : current.knowledgeBaseIds.filter((id) => id !== base.id) }))} />{base.name}</label>)}{!knowledgeBaseData?.length && <p className="text-sm text-muted-foreground">Create a knowledge base from Workspace first.</p>}<Button className="mt-2 w-fit" disabled={!data.access.canManageKnowledge} onClick={() => void save()}>Save knowledge access</Button></CardContent></Card><Card><CardHeader><CardTitle>Enabled agents</CardTitle><CardDescription>Choose which workspace agents can participate in this chat.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{data.access.canManageAgents && <div className="flex gap-2"><Select onValueChange={(value) => setAgentId(String(value))} value={agentId || null}><SelectTrigger className="min-w-0 flex-1"><SelectValue placeholder="Select an agent" /></SelectTrigger><SelectContent><SelectGroup>{(agentData ?? []).filter((agent) => !data.agents.some((link) => link.agentId === agent.id)).map((agent) => <SelectItem key={agent.id} value={agent.id}>{agent.name} · {agent.model}</SelectItem>)}</SelectGroup></SelectContent></Select><Button onClick={() => void addAgent()}>Add agent</Button></div>}{data.agents.map((link) => <div className="flex items-center justify-between rounded-lg border px-3 py-2 text-sm" key={link.id}><div><p className="font-medium">{link.agent.name}</p><p className="text-xs text-muted-foreground">{link.agent.model}</p></div>{data.access.canManageAgents && <Button onClick={() => void removeAgent(link.agentId)} size="sm" variant="ghost">Remove</Button>}</div>)}</CardContent></Card></div>;
}
